# 01_Yen – Prepare Data + Data Integration

**Thành viên:** Yến  
**Chủ đề:** Dữ liệu sản phẩm Tivi

## Nguồn dữ liệu
- Web Crawling: https://www.dienmayxanh.com/tivi
- External Dataset: https://www.kaggle.com/datasets/promptcloud/walmart-product-listing/versions/1

## Đầu ra
- tivi.xlsx
- walmart_tv.xlsx
- unified_static_master.xlsx
- dynamic_data.xlsx
- merged_data.csv
- merged_data.xlsx

## 1. Import thư viện

In [6]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import numpy as np

## 2. Đọc dữ liệu Static

In [8]:
dmx = pd.read_csv("tivi.csv")
wm = pd.read_csv("walmart_tv.csv")

print("Điện Máy Xanh:", dmx.shape)
print("Walmart:", wm.shape)

display(dmx.head())
display(wm.head())

Điện Máy Xanh: (302, 10)
Walmart: (387, 26)

,product_name,sale_price,tv_type,screen_size,resolution,screen_type,operating_system,ram,rom,release_year
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,18390000.0,Smart Tivi QNED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,webOS 26,Hãng không công bố,Hãng không công bố,2026
1,Google Tivi Sony 4K 65 inch K-65S25VM2,19990000.0,Google Tivi,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2025
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,7690000.0,Google Tivi QLED,40 inch,Full HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,1 GB,8 GB,2025
3,Google Tivi Sony 32 inch KD-32W830K,7690000.0,Google Tivi,32 inch,HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2022
4,Google Tivi QLED TCL 4K 65 inch 65P7L,18490000.0,Google Tivi QLED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,2 GB,16 GB,2026

,Uniq Id,Crawl Timestamp,Pageurl,Website,Title,Num Of Reviews,Average Rating,Number Of Ratings,Model Num,Sku,...,Carrier,Color Category,Internal Memory,Screen Size,Specifications,Five Star,Four Star,Three Star,Two Star,One Star
0,e2ba26ccfde2e975cbeeb827114243a5,2020-10-05 05:11:01 +0000,https://www.walmart.com/ip/Newest-OTA-TV-Stick...,walmart.com,fitup:9761 Newest OTA TV Stick Dongle Better T...,NaN,NaN,0.0,NaN,624090153,...,NaN,NaN,NaN,NaN,Brand : fitup:9761 | Product Name : Newest OTA...,NaN,NaN,NaN,NaN,NaN
1,221fd622fa04366fbc1320dcff9d65b7,2020-10-16 05:37:09 +0000,https://www.walmart.com/ip/HDMI-WiFi-Display-D...,walmart.com,firlar HDMI WiFi Display Dongle YouTube Netfli...,NaN,1.0,1.0,NaN,493943378,...,NaN,NaN,NaN,NaN,Number of Customer Ratings : 1 | Color : Black...,0.0,0.0,0.0,0.0,1.0
2,8fcfdc2d143ded0af11dd466c54d28fc,2020-10-10 02:59:10 +0000,https://www.walmart.com/ip/Luminoodle-Bias-Lig...,walmart.com,Power Practical Luminoodle Professional Bias L...,NaN,5.0,0.0,NaN,602540595,...,NaN,NaN,NaN,NaN,Brand : Power Practical | manufacturer_part_nu...,3.0,0.0,0.0,0.0,0.0
3,b580da63c637c3d4bcd1ef29aafa26d3,2020-10-10 03:04:36 +0000,https://www.walmart.com/ip/Sansui-40-Inch-1080...,walmart.com,Sansui Sansui 40-Inch 1080p FHD DLED TV (S40P2...,NaN,4.5,4.5,NaN,265972118,...,NaN,NaN,NaN,40\inch,Display Technology : LED | Resolution : 1080p ...,3.0,0.0,1.0,0.0,0.0
4,04ee9f3bc8b34db22cc77bac771ccfa3,2020-10-07 02:53:36 +0000,https://www.walmart.com/ip/TV-JTV19DC-RV-Built...,walmart.com,"Jensen JENSEN JTV19DC HD Ready 19"" Inch 12V LE...",2.0,3.0,3.0,JTV19DC,54012919,...,NaN,NaN,NaN,19inch,Display Technology : LED | Resolution : 1080p ...,1.0,0.0,0.0,0.0,1.0

## 3. Kiểm tra dữ liệu

In [9]:
print("Cột Điện Máy Xanh:")
print(dmx.columns.tolist())

print("\nCột Walmart:")
print(wm.columns.tolist())

print("\nSố dòng trùng:")
print("Điện Máy Xanh:", dmx.duplicated().sum())
print("Walmart:", wm.duplicated().sum())

Cột Điện Máy Xanh:
['product_name', 'sale_price', 'tv_type', 'screen_size', 'resolution', 'screen_type', 'operating_system', 'ram', 'rom', 'release_year']

Cột Walmart:
['Uniq Id', 'Crawl Timestamp', 'Pageurl', 'Website', 'Title', 'Num Of Reviews', 'Average Rating', 'Number Of Ratings', 'Model Num', 'Sku', 'Upc', 'Manufacturer', 'Model Name', 'Price', 'Monthly Price', 'Stock', 'Carrier', 'Color Category', 'Internal Memory', 'Screen Size', 'Specifications', 'Five Star', 'Four Star', 'Three Star', 'Two Star', 'One Star']

Số dòng trùng:
Điện Máy Xanh: 0
Walmart: 0

## 4. Đồng bộ tên cột

In [10]:
dmx = dmx.rename(columns={
    "product_name": "product_name",
    "sale_price": "price",
    "tv_type": "tv_type",
    "screen_size": "screen_size",
    "resolution": "resolution",
    "screen_type": "screen_type",
    "operating_system": "operating_system",
    "ram": "ram",
    "rom": "rom",
    "release_year": "release_year"
})

wm = wm.rename(columns={
    "Title": "product_name",
    "Price": "price",
    "Manufacturer": "manufacturer",
    "Model Name": "model_name",
    "Screen Size": "screen_size",
    "Average Rating": "rating",
    "Num Of Reviews": "num_reviews",
    "Specifications": "specifications"
})

print("Đã chuẩn hóa tên cột.")

Đã chuẩn hóa tên cột.

## 5. pd.concat() – Unified Static Master Table

In [11]:
cols = [
    "product_name", "price", "tv_type", "screen_size",
    "resolution", "screen_type", "operating_system",
    "ram", "rom", "release_year",
    "manufacturer", "model_name", "rating",
    "num_reviews", "specifications", "source"
]

dmx = dmx.reindex(columns=cols[:-1])
dmx["source"] = "dienmayxanh"

wm = wm.reindex(columns=cols[:-1])
wm["source"] = "walmart"

unified_static_master = pd.concat(
    [dmx, wm],
    ignore_index=True
)

print("Kích thước:", unified_static_master.shape)
display(unified_static_master.head())

Kích thước: (689, 16)

,product_name,price,tv_type,screen_size,resolution,screen_type,operating_system,ram,rom,release_year,manufacturer,model_name,rating,num_reviews,specifications,source
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,18390000.0,Smart Tivi QNED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,webOS 26,Hãng không công bố,Hãng không công bố,2026,NaN,NaN,NaN,NaN,NaN,dienmayxanh
1,Google Tivi Sony 4K 65 inch K-65S25VM2,19990000.0,Google Tivi,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2025,NaN,NaN,NaN,NaN,NaN,dienmayxanh
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,7690000.0,Google Tivi QLED,40 inch,Full HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,1 GB,8 GB,2025,NaN,NaN,NaN,NaN,NaN,dienmayxanh
3,Google Tivi Sony 32 inch KD-32W830K,7690000.0,Google Tivi,32 inch,HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2022,NaN,NaN,NaN,NaN,NaN,dienmayxanh
4,Google Tivi QLED TCL 4K 65 inch 65P7L,18490000.0,Google Tivi QLED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,2 GB,16 GB,2026,NaN,NaN,NaN,NaN,NaN,dienmayxanh

In [12]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
unified_static_master.to_excel(
    "F:/AI code/unified_static_master.xlsx",
    index=False
)
print("Đã xuất unified_static_master.xlsx")

Đã xuất unified_static_master.xlsx

## 6. Tạo Dynamic Data

In [14]:
np.random.seed(42)

dynamic = pd.DataFrame()
dynamic["product_name"] = unified_static_master["product_name"]
dynamic["monthly_views"] = np.random.randint(100, 10000, len(unified_static_master))
dynamic["monthly_orders"] = np.random.randint(5, 500, len(unified_static_master))
dynamic["customer_rating"] = np.round(
    np.random.uniform(3.0, 5.0, len(unified_static_master)), 1
)
dynamic["stock_quantity"] = np.random.randint(0, 200, len(unified_static_master))
dynamic["data_date"] = pd.date_range(
    start="2026-01-01",
    periods=len(unified_static_master),
    freq="D"
)

display(dynamic.head())
print("Kích thước:", dynamic.shape)

,product_name,monthly_views,monthly_orders,customer_rating,stock_quantity,data_date
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,7370,453,3.2,145,2026-01-01
1,Google Tivi Sony 4K 65 inch K-65S25VM2,960,373,4.3,66,2026-01-02
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,5490,492,4.5,41,2026-01-03
3,Google Tivi Sony 32 inch KD-32W830K,5291,292,4.7,117,2026-01-04
4,Google Tivi QLED TCL 4K 65 inch 65P7L,5834,38,3.2,124,2026-01-05

Kích thước: (689, 6)

In [17]:
dynamic.to_excel(
    "F:/AI code/dynamic_data.xlsx",
    index=False
)
print("Đã xuất dynamic_data.xlsx")

Đã xuất dynamic_data.xlsx

## 7. pd.merge() – Tích hợp Static và Dynamic Data

**Loại JOIN: Left Join**

Chọn Left Join để giữ toàn bộ sản phẩm trong Unified Static Master Table. Nếu thiếu dữ liệu động tương ứng thì sản phẩm tĩnh vẫn được giữ lại.

In [ ]:
merged_data = pd.merge(
    unified_static_master,
    dynamic,
    on="product_name",
    how="left"
)

print("Kích thước sau merge:", merged_data.shape)
display(merged_data.head())

Kích thước sau merge: (689, 21)

,product_name,price,tv_type,screen_size,resolution,screen_type,operating_system,ram,rom,release_year,...,model_name,rating,num_reviews,specifications,source,monthly_views,monthly_orders,customer_rating,stock_quantity,data_date
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,18390000.0,Smart Tivi QNED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,webOS 26,Hãng không công bố,Hãng không công bố,2026,...,NaN,NaN,NaN,NaN,dienmayxanh,7370,453,3.2,145,2026-01-01
1,Google Tivi Sony 4K 65 inch K-65S25VM2,19990000.0,Google Tivi,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2025,...,NaN,NaN,NaN,NaN,dienmayxanh,960,373,4.3,66,2026-01-02
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,7690000.0,Google Tivi QLED,40 inch,Full HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,1 GB,8 GB,2025,...,NaN,NaN,NaN,NaN,dienmayxanh,5490,492,4.5,41,2026-01-03
3,Google Tivi Sony 32 inch KD-32W830K,7690000.0,Google Tivi,32 inch,HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2022,...,NaN,NaN,NaN,NaN,dienmayxanh,5291,292,4.7,117,2026-01-04
4,Google Tivi QLED TCL 4K 65 inch 65P7L,18490000.0,Google Tivi QLED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,2 GB,16 GB,2026,...,NaN,NaN,NaN,NaN,dienmayxanh,5834,38,3.2,124,2026-01-05

## 8. Kiểm tra dữ liệu sau Merge

In [ ]:
print("Số dòng:", len(merged_data))
print("Số cột:", len(merged_data.columns))

print("\nCác cột:")
print(merged_data.columns.tolist())

print("\nGiá trị thiếu:")
display(merged_data.isna().sum())

print("\nSố dòng trùng:", merged_data.duplicated().sum())

Số dòng: 689
Số cột: 21

Các cột:
['product_name', 'price', 'tv_type', 'screen_size', 'resolution', 'screen_type', 'operating_system', 'ram', 'rom', 'release_year', 'manufacturer', 'model_name', 'rating', 'num_reviews', 'specifications', 'source', 'monthly_views', 'monthly_orders', 'customer_rating', 'stock_quantity', 'data_date']

Giá trị thiếu:

product_name          0
price                15
tv_type             387
screen_size         241
resolution          387
screen_type         387
operating_system    387
ram                 395
rom                 395
release_year        387
manufacturer        308
model_name          538
rating              578
num_reviews         653
specifications      307
source                0
monthly_views         0
monthly_orders        0
customer_rating       0
stock_quantity        0
data_date             0
dtype: int64

Số dòng trùng: 0

## 9. Xuất dữ liệu cuối cùng

In [ ]:
merged_data.to_csv(
    "D:/DataAI/merged_data.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Đã xuất merged_data.csv")

Đã xuất merged_data.csv

# 02_Linh – QDRANT

**Thành viên:** Linh  
**Nối tiếp:** Yến – Prepare Data + Data Integration → Linh – Qdrant → Dương – SQLite + Cleaning → Hải – Univariate EDA

## Mục tiêu
Xử lý dữ liệu merged_data.csv trên cơ sở dữ liệu Qdrant:
- Đưa dữ liệu vào Qdrant và tổ chức dữ liệu để lưu trữ.
- Thực hiện kiểm tra, truy vấn và tìm kiếm dữ liệu trên Qdrant.
- Kết nối Qdrant với Python để thao tác và khai thác dữ liệu.
- Kiểm tra kết quả lưu trữ và truy vấn dữ liệu.

In [20]:
import pandas as pd

df = pd.read_csv("merged_data.csv")

print("Số records:", len(df))
print("Số columns:", len(df.columns))

display(df.head())

Số records: 689
Số columns: 21

,product_name,price,tv_type,screen_size,resolution,screen_type,operating_system,ram,rom,release_year,...,model_name,rating,num_reviews,specifications,source,monthly_views,monthly_orders,customer_rating,stock_quantity,data_date
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,18390000.0,Smart Tivi QNED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,webOS 26,Hãng không công bố,Hãng không công bố,2026,...,NaN,NaN,NaN,NaN,dienmayxanh,7370,453,3.2,145,2026-01-01
1,Google Tivi Sony 4K 65 inch K-65S25VM2,19990000.0,Google Tivi,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2025,...,NaN,NaN,NaN,NaN,dienmayxanh,960,373,4.3,66,2026-01-02
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,7690000.0,Google Tivi QLED,40 inch,Full HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,1 GB,8 GB,2025,...,NaN,NaN,NaN,NaN,dienmayxanh,5490,492,4.5,41,2026-01-03
3,Google Tivi Sony 32 inch KD-32W830K,7690000.0,Google Tivi,32 inch,HD,Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,Hãng không công bố,16 GB,2022,...,NaN,NaN,NaN,NaN,dienmayxanh,5291,292,4.7,117,2026-01-04
4,Google Tivi QLED TCL 4K 65 inch 65P7L,18490000.0,Google Tivi QLED,65 inch,4K (Ultra HD),Đèn nền: <a href='https://www.dienmayxanh.com/...,Google TV,2 GB,16 GB,2026,...,NaN,NaN,NaN,NaN,dienmayxanh,5834,38,3.2,124,2026-01-05

In [18]:
#chọn dữ liệu để embedding
text_columns = [
    "product_name",
    "tv_type",
    "screen_size",
    "resolution",
    "screen_type",
    "operating_system",
    "ram",
    "rom",
    "release_year"
]

In [21]:
def create_text(row):
    return (
        f"Sản phẩm: {row['product_name']}. "
        f"Loại TV: {row['tv_type']}. "
        f"Kích thước: {row['screen_size']}. "
        f"Độ phân giải: {row['resolution']}. "
        f"Loại màn hình: {row['screen_type']}. "
        f"Hệ điều hành: {row['operating_system']}. "
        f"RAM: {row['ram']}. "
        f"ROM: {row['rom']}. "
        f"Năm ra mắt: {row['release_year']}."
    )

df["text"] = df.apply(create_text, axis=1)
display(df[["product_name", "text"]].head())

,product_name,text
0,Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA,Sản phẩm: Smart Tivi QNED LG AI 4K 65 inch 65Q...
1,Google Tivi Sony 4K 65 inch K-65S25VM2,Sản phẩm: Google Tivi Sony 4K 65 inch K-65S25V...
2,Google Tivi QLED TCL AI FHD 40 inch 40S5K,Sản phẩm: Google Tivi QLED TCL AI FHD 40 inch ...
3,Google Tivi Sony 32 inch KD-32W830K,Sản phẩm: Google Tivi Sony 32 inch KD-32W830K....
4,Google Tivi QLED TCL 4K 65 inch 65P7L,Sản phẩm: Google Tivi QLED TCL 4K 65 inch 65P7...

In [22]:
%pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (6.1.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (5.17.0)
Requirement already satisfied: tokenizers>=0.19 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.14.0)
Requirement already satisfied: numpy>=1.24.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.5.3)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.18.1)
Requirement already satisfied: typing_extensions>=4.10.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.70.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\asus\appdata\roaming\python\python312\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.2->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.2->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python312\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.9.10)
Requirement already satisfied: typer in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.15.1)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.20)
Requirement already satisfied: h11>=0.16 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
#tạo embedding
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(
    df["text"].tolist(),
    show_progress_bar=True
)

print("Số vector:", len(embeddings))
print("Số chiều:", len(embeddings[0]))

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6287.67it/s]
Batches: 100%|██████████| 22/22 [00:06<00:00,  3.63it/s]

Số vector: 689
Số chiều: 384

In [24]:
%pip install qdrant_client

Requirement already satisfied: qdrant_client in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (1.19.1)
Requirement already satisfied: grpcio>=1.41.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (1.84.0)
Requirement already satisfied: httpx[http2]>=0.20.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (0.28.1)
Requirement already satisfied: numpy>=1.26 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (2.5.3)
Requirement already satisfied: portalocker<4.0,>=2.7.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (3.2.0)
Requirement already satisfied: protobuf>=3.20.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (7.36.2)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (2.13.5)
Requirement already satisfied: urllib3<3,>=1.26.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from qdrant_client) (2.8.0)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\asus\appdata\roaming\python\python312\site-packages (from grpcio>=1.41.0->qdrant_client) (4.16.0)
Requirement already satisfied: anyio in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (4.15.1)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (1.0.9)
Requirement already satisfied: idna in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (3.20)
Requirement already satisfied: h2<5,>=3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx[http2]>=0.20.0->qdrant_client) (4.4.1)
Requirement already satisfied: h11>=0.16 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx[http2]>=0.20.0->qdrant_client) (0.16.0)
Requirement already satisfied: pywin32>=226 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from portalocker<4.0,>=2.7.0->qdrant_client) (312)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant_client) (0.4.4)
Requirement already satisfied: hyperframe<7,>=6.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant_client) (4.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
%pip install --upgrade --force-reinstall pywin32

Collecting pywin32
  Obtaining dependency information for pywin32 from https://files.pythonhosted.org/packages/03/d9/77040d3b43df3f3be32ea289433d660d2727f5ba327bc73be835127d9d60/pywin32-312-cp312-cp312-win_amd64.whl.metadata
  Using cached pywin32-312-cp312-cp312-win_amd64.whl.metadata (11 kB)
Using cached pywin32-312-cp312-cp312-win_amd64.whl (6.9 MB)
Installing collected packages: pywin32
  Attempting uninstall: pywin32
    Found existing installation: pywin32 312
    Uninstalling pywin32-312:
      Successfully uninstalled pywin32-312
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\~ywin32_system32\\pywintypes312.dll'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
#kết nối qdrant
from qdrant_client import QdrantClient

client = QdrantClient(path="./qdrant_storage_linh")

collection_name = "tv_products"

In [29]:
# Tạo Collection
from qdrant_client.models import Distance, VectorParams

if client.collection_exists(collection_name):
    client.delete_collection(collection_name)

client.create_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

True

In [30]:
# Tạo Point
from qdrant_client.models import PointStruct

payloads = (
    df.drop(columns=["text"])
      .fillna("")
      .to_dict(orient="records")
)

points = []

for i, (embedding, payload) in enumerate(
    zip(embeddings, payloads)
):
    points.append(
        PointStruct(
            id=i,
            vector=embedding.tolist(),
            payload=payload
        )
    )

In [31]:
# Ingest vào Qdrant
client.upsert(
    collection_name=collection_name,
    points=points
)

print("Đã ingest dữ liệu vào Qdrant!")

Đã ingest dữ liệu vào Qdrant!

In [32]:
# Kiểm tra số lượng records
info = client.get_collection(collection_name)

print("Số records trong Qdrant:",
      info.points_count)

Số records trong Qdrant: 689

In [33]:
# Lấy record mẫu
records, next_page = client.scroll(
    collection_name=collection_name,
    limit=5,
    with_payload=True,
    with_vectors=False
)

for record in records:
    print("ID:", record.id)
    print("Product:", record.payload.get("product_name"))
    print("Price:", record.payload.get("sale_price"))
    print("-" * 50)

ID: 0
Product: Smart Tivi QNED LG AI 4K 65 inch 65QNED70BSA
Price: None
--------------------------------------------------
ID: 1
Product: Google Tivi Sony 4K 65 inch K-65S25VM2
Price: None
--------------------------------------------------
ID: 2
Product: Google Tivi QLED TCL AI FHD 40 inch 40S5K
Price: None
--------------------------------------------------
ID: 3
Product: Google Tivi Sony 32 inch KD-32W830K
Price: None
--------------------------------------------------
ID: 4
Product: Google Tivi QLED TCL 4K 65 inch 65P7L
Price: None
--------------------------------------------------

In [34]:
# Query / Similarity Search
query = "Tivi LG 4K 65 inch"

query_vector = model.encode(query).tolist()

results = client.query_points(
    collection_name=collection_name,
    query=query_vector,
    limit=5,
    with_payload=True
).points

In [35]:
for result in results:
    print("Score:", round(result.score, 4))
    print("Product:",
          result.payload.get("product_name"))
    print("Price:",
          result.payload.get("sale_price"))
    print("Resolution:",
          result.payload.get("resolution"))
    print("-" * 50)

Score: 0.5909
Product: Google Tivi RGB - Mini LED TCL 4K 75 inch 75RM7L
Price: None
Resolution: 4K (Ultra HD)
--------------------------------------------------
Score: 0.5771
Product: Google Tivi QLED TCL AI 4K 75 inch 75C69B
Price: None
Resolution: 4K (Ultra HD)
--------------------------------------------------
Score: 0.5745
Product: Google Tivi QLED TCL 4K 65 inch 65T6D
Price: None
Resolution: 4K (Ultra HD)
--------------------------------------------------
Score: 0.5712
Product: Google Tivi QLED TCL 4K 65 inch 65P7L
Price: None
Resolution: 4K (Ultra HD)
--------------------------------------------------
Score: 0.5695
Product: Google Tivi True RGB Sony AI 4K 65 inch K-65XR70M2
Price: None
Resolution: 4K (Ultra HD)
--------------------------------------------------